### ISSUE TITLE
some small issues~

### ISSUE THREAD

**Issue by jellyr** [cbaggers/cepl.examples#1]
It seems that in  cepl.examples.asd
:depends-on (#:cepl.sdl2 #:cepl.camera #:dendrite #:skitter
               #:cepl.skitter.sdl2 #:livesupport
               #:cepl.devil #:classimp #:split-sequence )
should add a moudle        #:temporal-functions

because in example moving-triangles, you use the ttm moudle.

I do not know if I am right, I just change the code to get the example run successfully on my win32 platform, thanks for your time, the project is great!

**Comment by cbaggers** [comment]
@jellyr thats a great catch! Thankyou.
Also really cool to hear you are able to get some of the examples working. I would love to hear how you get on

**Comment by cbaggers** [comment]
fixed issue https://github.com/cbaggers/cepl.examples/commit/3f581804e697b315614100f3fa74afb410096818

Turns out the example didnt need it, but I should add a temporal-function example at some point so I'm adding the dependency too
