### ISSUE TITLE
Compute example

### ISSUE THREAD

**Issue by ghost** [cbaggers/cepl.examples#11]
Could we put the basic compute example here as well.

(in-package :cepl.examples)

(defvar data nil)
(defvar ssbo nil)

(defstruct-g (bah :layout :std-430)
(data (:int 10)))

(defun-g yay-compute (&uniform (woop bah :ssbo))
(declare (local-size :x 1 :y 1 :z 1))
(setf (aref (bah-data woop) (int (x gl-work-group-id)))
(int (x gl-work-group-id)))
(values))

(defpipeline-g test-compute ()
:compute yay-compute)

(defun reset ()
(setf data (make-gpu-array nil :dimensions 1 :element-type 'bah))
(setf ssbo (make-ssbo data)))

(defun test ()
(reset)
(map-g #'test-compute (make-compute-space 10)
:woop ssbo))

;; In repl
(reset)
(test)
(pull-g data) ; --> (((0 1 2 3 4 5 6 7 8 9)))

**Comment by cbaggers** [comment]
Good call, i'll do this soon

**Comment by ghost** [comment]
Should there be a mention of using barriers? For example, for summing the resulting values to the last cell.

**Comment by cbaggers** [comment]
@tsili that sounds like a good idea to me.  I couldnt get this out of my head today so I just pushed an tested example here https://github.com/cbaggers/cepl.examples/blob/cepl-master/examples/compute.lisp

It's almost certain that it has a bug, but I'm on a mac right now and `<insert my usual fist waving rant about apple and gl here>`, so I'll test this later :)

Note it does require CEPL master as I just noticed I didnt have free for sync objects

**Comment by cbaggers** [comment]
It worked! It's on the cepl-master branch.

**Comment by ghost** [comment]
I played with this example a bit and found some interesting functionality. I'm not sure if I'm doing this right so I'll just ask.

With the yay-compute function defined as

```
(defun-g yay-compute (&uniform
                      (woop ssbo-test-data :ssbo)
                      (modifier :float))
  (declare (local-size :x 30 :y 1 :z 1))
  (when (not (eql (int (x gl-work-group-id))
                  0))
    (for (i 0) (< i 9) (++ i)
         (setf (aref (ssbo-test-data-vals woop)
                     (int (x gl-work-group-id)))
               0))
    (setf (aref (ssbo-test-data-vals woop)
                (int (x gl-work-group-id)))
          (int (x gl-work-group-id))))
  (barrier)
  (when (eql (int (x gl-work-group-id))
             0)
    (let ((sum (int 0)))
      (for (i 1) (< i 30) (++ i)
           (setf sum (+ sum
                        (aref (ssbo-test-data-vals woop)
                              i))))
      (setf (aref (ssbo-test-data-vals woop)
                  0)
            sum)))
  (values))
```

Or in words, after separating the work item 0 from the rest and having those burn some time before doing their thing, causes some non-expected outcomes when having the work item 0 do some summation.

Here is some example output where the first item should be the sum of the rest. For one, the sum should not change and it should be 435.

(((117 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((146 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((117 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((194 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((93 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((104 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((66 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((119 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((117 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((90 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29))) 
(((90 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29)))

I have tried (local-size :x 30 :y 1 :z 1) and (local-size :x 1 :y 1 :z 1).
Aren't work items supposed to wait at the barrier for others before continuing or am I using a wrong function here?

Varjo seems to give two alternatives for the glsl depending on how the code is pulled

(pull-g 'run-compute) gives
```
("// compute-stage
#version 450

struct SSBO_TEST_DATA {
    int VALS[(30)];
};

layout(local_size_x = 30, local_size_y = 1, local_size_z = 1) in;

layout(std430) buffer _SSBO_WOOP
{
    int[30] VALS;
} WOOP;
uniform float MODIFIER;

void main()
{
    if (!(int(gl_WorkGroupID.x) == 0))
    {
        for (int I = 0;(I < 9);(++ I))
        {
            WOOP.VALS[int(gl_WorkGroupID.x)] = 0;
        }
        WOOP.VALS[int(gl_WorkGroupID.x)] = int(gl_WorkGroupID.x);
    }
    barrier();
    if ((int(gl_WorkGroupID.x) == 0))
    {
        int SUM = 0;
        for (int I0 = 1;(I0 < 30);(++ I0))
        {
            SUM = (SUM + WOOP.VALS[I0]);
        }
        WOOP.VALS[0] = SUM;
    }
    return;
}

")

```

(pull-g 'yay-compute) gives

```
"// compute-stage
#version 460

struct SSBO_TEST_DATA {
    int VALS[(30)];
};

layout(local_size_x = 10, local_size_y = 10, local_size_z = 10) in;

layout(std140) buffer _SSBO_WOOP
{
    int[30] VALS;
} WOOP;
uniform float MODIFIER;

void YAY_COMPUTE();

void YAY_COMPUTE()
{
    if (!(int(gl_WorkGroupID.x) == 0))
    {
        for (int I = 0;(I < 9);(++ I))
        {
            WOOP.VALS[int(gl_WorkGroupID.x)] = 0;
        }
        WOOP.VALS[int(gl_WorkGroupID.x)] = int(gl_WorkGroupID.x);
    }
    barrier();
    if ((int(gl_WorkGroupID.x) == 0))
    {
        int SUM = 0;
        for (int I0 = 1;(I0 < 30);(++ I0))
        {
            SUM = (SUM + WOOP.VALS[I0]);
        }
        WOOP.VALS[0] = SUM;
    }
    return;
}

void main()
{
    YAY_COMPUTE();
    return;
}

"
```

Here is the appropriate khronos registry page about [barriers](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/barrier.xhtml)
According to the registry page, both alternatives of the glsl should be valid with compute shaders and give the same result.

**Comment by cbaggers** [comment]
I understand the `pull-g` differences so I'll explain those first, the other stuff I'll have a poke around and learn about (all new to me too :))

When a gpu function is defined, CEPL doesnt yet know what it will be used for, it could be used as a whole stage or as a helper function in a stage, so it conservatively generates some simple stages which call your function from 'main'. If it finds one that works it caches that code and assumes all is ok.

When you `(pull-g '(yay-compute))` that is what you are seeing.

When a pipeline is defined, CEPL knows exactly what the functions are being used for an so is able to generate the actual code that will be pushed to the gpu. This is why you can define a gpu-function that uses `gl-local-invocation-id` and all will be fine, but if you tried to use that function as a vertex stage it will throw an error. When you `(pull-g 'run-compute)` you are seeing the 'final' code. This is also why sometimes you can get `nil` from pulling a pipeline, it hasn't been compiled yet (it does this as late as possible) so in those cases you can `(map-g #'the-pipeline nil)` and then `(pull-g 'the-pipeline)`.

Next, I'll play with your example, I'll get back to you as soon as I know whats up :)

**Comment by cbaggers** [comment]
I may be misunderstanding you shader so I'll just note a couple things I spot in it and maybe you could tell me if those are the behaviour you were going for or if I have made some mistakes regarding the glsl spec:

`(local-size :x 30 :y 1 :z 1)` Tells us we are going to have 30 invocations per work group, and (as it wasnt specified in the issue) Im gonna guess the compute space is still 30.

So this will mean the compute shader will be run 900 times. The compute space tells us the number of work-groups.

The wiki tells us that: 

> For any given static instance of barrier in a compute shader, all
> invocations within a single work group must enter it before any are
> allowed to continue beyond it.

So 30 workgroups are going to start.

Workgroup 0 start it's 30 invocations that all do nothing before the barrier and so then they all hit it they all continue and do the second half (we will come back to these folks)

meanwhile (or before..or after) the other workgroups are doing things. They set one element of the ssbo to 0, they do this 9 times. Then the set it to their workgroup id once. Each group has 30 invocations doing the exact same thing and all waiting until the other invocations are done. However they are not caring about the other work groups, they can happen in any order (because barriers only hold within a single workgroup).

So back to workgroup 0, it starts summing up the values from the ssbo. It has 30 invocations doing this and they all may write something slightly different as all can run in any order, and so are the other workgroups, so depending on which workgroups have started or finished (which we dont know as barriers only work within groups) the contents of the ssbo could be different.

So I think there is a problem here. If you change the space you are mapping over to `(make-compute-space 1)` and `yay-compute` to:

```
(defun-g yay-compute (&uniform
                      (woop ssbo-test-data :ssbo)
                      (modifier :float))
  (declare (local-size :x 30 :y 1 :z 1))
  (let ((id (int (x gl-local-invocation-id))))
    (when (/= id 0)
      (setf (aref (ssbo-test-data-vals woop) id) id))
    (barrier)
    (when (= id 0)
      (let ((sum (int 0)))
        (for (i 1) (< i 30) (++ i)
             (incf sum (aref (ssbo-test-data-vals woop) i)))
        (setf (aref (ssbo-test-data-vals woop) 0) sum)))
    (values)))
```

You get:

```
(((435 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
   28 29)))
```

And I get that result each time it's run.

I hope this helps

**Comment by ghost** [comment]
Yes it helps. Thank you.

I had falsely assumed that local size was used to DIVIDE up the compute space. Now it makes perfect sense.

**Comment by cbaggers** [comment]
Great! good luck with the computing!
