### ISSUE TITLE
model-parser broken

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/cepl.examples#3]
I was trying to get instancing to work...

classimp?

**Comment by cbaggers** [comment]
Oh yeah. How had I not noticed that? It looks like I commented it out here: f3bc4054f0da392578de5c577299206522a8f16e

What I expect is that I was on a platform which didnt have classimp available and I commented it out to avoid the build error. I then would have forgotten and merged the change with the code that changed the examples to use sdl2.image

I will undo this mistake

**Comment by stacksmith** [comment]
Understandable.  Glad I came across this.

**Comment by cbaggers** [comment]
Oh yeah. How had I not noticed that? It looks like I commented it out here: f3bc4054f0da392578de5c577299206522a8f16e

What I expect is that I was on a platform which didnt have classimp available and I commented it out to avoid the build error. I then would have forgotten and merged the change with the code that changed the examples to use sdl2.image

I will undo this mistake
