### ISSUE TITLE
Symbol "REGISTER-EVENT-LISTENER" not found in the CEPL package.

### ISSUE THREAD

**Issue by npatrick04** [cbaggers/cepl.examples#8]
I think the cepl.examples repo is a bit out of date.  I tried loading this from the quicklisp cepl.

**Comment by cbaggers** [comment]
Hi @npatrick04, `REGISTER-EVENT-LISTENER` is not part of cepl.examples but it is part of CEPL. Is there a chance you have a local copy of `cepl.sdl2` in your local-projects folder?

**Comment by npatrick04** [comment]
I updated my quicklisp distro, and removed a couple packages I'd cloned from my local projects and it's working fine now.  Thanks.

**Comment by cbaggers** [comment]
No probs :)
